from typing import List, Tuple

class KmerFinder:
    def __init__(self, kmers_and_offsets: List[Tuple[str, int]]): ...
    def kmers_present(self, __sequence: str) -> bool: ...

def quick_and_dirty_upper(__sequence: str) -> str: ...
